version: '3.3'

services:

  hydra-migrate:
    # image: oryd/hydra:v0.11.6-alpine
    image: oryd/hydra:v0.10.10-alpine
    links:
      - postgresd:postgresd
    entrypoint: hydra migrate sql postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
    environment:
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
      - SYSTEM_SECRET=b_ZVB1gZheec03slD7Pamnj1IQj0QAA4


  oathkeeper-migrate:
    image: oryd/oathkeeper:v0.0.29
    links:
      - postgresd:postgresd
    entrypoint: oathkeeper migrate postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
    environment:
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
      - SYSTEM_SECRET=b_ZVB1gZheec03slD7Pamnj1IQj0QAA4

