version: '3.3'

services:

  hydra:
    # image: oryd/hydra:v0.11.6-alpine
    image: oryd/hydra:v0.10.10-alpine
    ports:
      - "4444:4444"
      - "4445:4445"
    volumes:
      - hydravolume:/root
    links:
      - postgresd:postgresd
    entrypoint: hydra host --dangerous-force-http --dangerous-auto-logon --skip-tls-verify
    environment:
      - SYSTEM_SECRET=b_ZVB1gZheec03slD7Pamnj1IQj0QAA4
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
      - ISSUER=http://localhost:4444/
      - CONSENT_URL=http://localhost:9020/consent
      - FORCE_ROOT_CLIENT_CREDENTIALS=admin:demo-password
      - CLIENT_ID=admin
      - CLIENT_SECRET=demo-password 
      - CLUSTER_URL=http://localhost:4444/


  hydra-migrate:
    # image: oryd/hydra:v0.11.6-alpine
    image: oryd/hydra:v0.10.10-alpine
    links:
      - postgresd:postgresd
    entrypoint: hydra migrate sql postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
    environment:
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
      - SYSTEM_SECRET=b_ZVB1gZheec03slD7Pamnj1IQj0QAA4


  postgresd:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra


  consent-app:
    image: oryd/hydra-consent-app-express
    ports:
      - "9020:3000"
    links:
      - hydra:hydra
    environment:
      - HYDRA_CLIENT_ID=consent-app
      - HYDRA_CLIENT_SECRET=consent-secret
      - HYDRA_URL=http://hydra:4444
      - NODE_TLS_REJECT_UNAUTHORIZED=0


  oathkeeper:
    image: oryd/oathkeeper:v0.0.29
    entrypoint: oathkeeper serve all
    ports:
      - "4455:4455"
      - "4456:4456"
    links:
      - postgresd:postgresd
      - hydra:hydra
    environment:
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
      - ISSUER_URL=http://hydra:4444/
      - HYDRA_URL=http://hydra:4444/
      - HYDRA_JWK_SET_ID=oathkeeper:id-token-2
      - HYDRA_CLIENT_ID=oathkeeper-client-2
      - HYDRA_CLIENT_SECRET=secret_key
      - BACKEND_URL=http://api.local/
      - VIRTUAL_HOST=oathkeeper.local


  oathkeeper-migrate:
    image: oryd/oathkeeper:v0.0.29
    links:
      - postgresd:postgresd
    entrypoint: oathkeeper migrate postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
    environment:
      - DATABASE_URL=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable
      - SYSTEM_SECRET=b_ZVB1gZheec03slD7Pamnj1IQj0QAA4


volumes:
  hydravolume:
    driver: local

